[package]
org = "ballerina"
name = "websocket"
version = "2.6.0"
authors = ["Ballerina"]
keywords = ["ws", "network", "bi-directional", "streaming", "service", "client"]
repository = "https://github.com/ballerina-platform/module-ballerina-websocket"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.4.0"

[[platform.java11.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "websocket-native"
version = "2.6.0"
path = "../native/build/libs/websocket-native-2.6.0-SNAPSHOT.jar"

[[platform.java11.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "http-native"
version = "2.6.0"
path = "./lib/http-native-2.6.0-20221124-124400-2b86399.jar"

[[platform.java11.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "mime-native"
version = "2.6.0"
path = "./lib/mime-native-2.6.0-20221122-182800-8ec96a8.jar"

[[platform.java11.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "constraint-native"
version = "1.1.0"
path = "./lib/constraint-native-1.1.0-20221122-134300-fc2d3aa.jar"

[[platform.java11.dependency]]
path = "./lib/netty-common-4.1.77.Final.jar"

[[platform.java11.dependency]]
path = "./lib/netty-buffer-4.1.77.Final.jar"

[[platform.java11.dependency]]
path = "./lib/netty-transport-4.1.77.Final.jar"

[[platform.java11.dependency]]
path = "./lib/netty-resolver-4.1.77.Final.jar"

[[platform.java11.dependency]]
path = "./lib/netty-handler-4.1.77.Final.jar"

[[platform.java11.dependency]]
path = "./lib/netty-codec-http-4.1.77.Final.jar"

[[platform.java11.dependency]]
path = "./lib/netty-codec-4.1.77.Final.jar"

[[platform.java11.dependency]]
path = "./lib/netty-handler-proxy-4.1.77.Final.jar"

[[platform.java11.dependency]]
path = "../test-utils/build/libs/websocket-test-utils-2.6.0-SNAPSHOT.jar"
scope = "testOnly"
