[plugin]
id = "websocket-compiler-plugin"
class = "io.ballerina.stdlib.websocket.plugin.WebSocketCompilerPlugin"

[[dependency]]
path = "../compiler-plugin/build/libs/compiler-plugin-@project.version@.jar"
