[plugin]
id = "websocket-compiler-plugin"
class = "io.ballerina.stdlib.websocket.plugin.WebSocketCompilerPlugin"

[[dependency]]
path = "../websocket-compiler-plugin/build/libs/websocket-compiler-plugin-@project.version@.jar"
