[plugin]
id = "websocket-compiler-plugin"
class = "io.ballerina.stdlib.websocket.plugin.WebSocketCompilerPlugin"

[[dependency]]
path = "../websocket-compiler-plugin/build/libs/websocket-compiler-plugin-1.2.0-beta.2-SNAPSHOT.jar"
