[[dependency]]
org = "ballerina"
name = "io"
version = "0.6.0-alpha5"

[[dependency]]
org = "ballerina"
name = "mime"
version = "1.1.0-alpha5"

[[dependency]]
org = "ballerina"
name = "time"
version = "2.0.0-alpha5"

[[dependency]]
org = "ballerina"
name = "http"
version = "1.1.0-alpha5"
